<?php

namespace Doyo\Bridge\CodeCoverage\Report;

use SebastianBergmann\CodeCoverage\Report\Xml\Facade;

class XML extends AbstractReportProcessor
{
    protected $defaultOptions = [
        'target' => 'build/xml'
    ];

    protected function createProcessor(array $options)
    {
        $options['version'] = 'DoyoLabs-CustomCoverage';
        return parent::createProcessor($options); // TODO: Change the autogenerated stub
    }


    public function getProcessorClass(): string
    {
        return Facade::class;
    }

    public function getOutputType(): string
    {
        return static::OUTPUT_DIR;
    }

    public function getType(): string
    {
        return 'xml';
    }
}
